# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Xavier Raffin
tagline:          'Software Architect'
description:      'Personnal website of a CTO at <a href="https://hottakes.com" target="_blank">HotTakes</a>.'
url:              http://xavierraffin.com
baseurl:          /
googleanalytics:  UA-36576424-1
disqus:           xavierraffin

# Allow future post to appear
future:           true

author:
  name:           'Xavier Raffin'
  twitter:        https://twitter.com/xavierraffin
  linkedin:       https://www.linkedin.com/in/xavierraffin 
  github:         https://github.com/xavierraffin   
  stack:          http://stackoverflow.com/users/1734467/xavierraffin

paginate:         5

# Custom vars
version:          0.1

gems:
  - jekyll-paginate
  - jekyll-redirect-from
